-- Create tag management tables for centralized tag storage

-- Create news_tags table with single row constraint
CREATE TABLE IF NOT EXISTS news_tags (
    tags text null,
    id integer generated by default as identity not null,
    constraint news_tags_pkey primary key (id)
);

-- Create product_tags table with single row constraint
CREATE TABLE IF NOT EXISTS product_tags (
    tags text null,
    id integer generated by default as identity not null,
    constraint product_tags_pkey primary key (id)
);

-- Insert initial empty tag arrays
INSERT INTO news_tags (id, tags) VALUES (1, '[]') ON CONFLICT DO NOTHING;
INSERT INTO product_tags (id, tags) VALUES (1, '[]') ON CONFLICT DO NOTHING;

-- Add constraints to ensure only one row exists in each table
ALTER TABLE news_tags ADD CONSTRAINT IF NOT EXISTS news_tags_single_row CHECK (id = 1);
ALTER TABLE product_tags ADD CONSTRAINT IF NOT EXISTS product_tags_single_row CHECK (id = 1);

-- Add some sample tags for testing (optional)
-- UPDATE news_tags SET tags = '["Tin Hiệp hội", "Chính sách", "Sự kiện", "Thông báo"]';
-- UPDATE product_tags SET tags = '["Công nghệ", "Giải pháp", "Dịch vụ", "Phần mềm"]'; 