-- Create product_requests table
CREATE TABLE public.product_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NOT NULL,
    username text NULL,
    phone_number text NULL,
    city text NULL,
    district text NULL,
    specific_address text NULL,
    org_type text NULL
) TABLESPACE pg_default;

-- Add primary key constraint
ALTER TABLE public.product_requests ADD CONSTRAINT product_requests_pkey PRIMARY KEY (id);

-- Add RLS (Row Level Security) if needed
ALTER TABLE public.product_requests ENABLE ROW LEVEL SECURITY;

-- Grant necessary permissions
GRANT ALL ON TABLE public.product_requests TO authenticated;
GRANT ALL ON TABLE public.product_requests TO service_role; 