-- Create news_tags table with single row constraint
CREATE TABLE public.news_tags (
  tags text null,
  id integer generated by default as identity not null,
  constraint news_tags_pkey primary key (id)
) TABLESPACE pg_default;

-- Insert the initial single row with empty tags
INSERT INTO public.news_tags (id, tags) VALUES (1, '[]');

-- Add a constraint to ensure only one row exists
ALTER TABLE public.news_tags ADD CONSTRAINT news_tags_single_row CHECK (id = 1); 